### ISSUE TITLE
Should the length threshold for skipping writing nc files be an argument?

### ISSUE THREAD

**Issue by richardsc** [jklymak/pyglider#16]
See: https://github.com/jklymak/pyglider/blob/92bfa4e1e480cf0c2f7f3398719a6a16cc8eb0ac/pyglider/seaexplorer.py#L136

It occured to me that hardcoding that value could be problematic (e.g. for very shallow dives with `.sub.` realtime data). I don't have the experience to be confident adding as an arg to `raw_to_rawnc()` though.

**Comment by jklymak** [comment]
In python its often a good idea to add things like this as kwargs: `raw_to_rawnc(.... min_samples_in_file=5)` so the kwarg has a default, and doesn't have to be specified, but the user could modify if they like.
