### ISSUE TITLE
Problem running the provided slocum example

### ISSUE THREAD

**Issue by nbronikowski** [jklymak/pyglider#5]
Hi Jody,

Attempting long overdue switch from MATLAB to python :-) 
Trying to make the slocum example work in pyglider, so far 2 issues:

1) on line 212 I had to remove `.upper()` and change **'CAC'** to **'cac'** to find the cache files in `fname = cachedir + '/' + meta['sensor_list_crc'].upper() + '.CAC'`

2) it runs and generates L1 timeseries netcdf files and netcdf files for the profiles, but I get the following error: 

```
Traceback (most recent call last):
  File "process_deploymentRealTime.py", line 51, in <module>
    outname = ncprocess.make_L2_gridfiles(outname, griddir, deploymentyaml)
  File "/home/data-process/Desktop/pyglider-master/pyglider/ncprocess.py", line 157, in make_L2_gridfiles
    profile_meta['profile_time_start'] )
KeyError: 'profile_time_start'
```

Hope things are well!

Best,
Nicolai

**Comment by jklymak** [comment]
Thanks, this was the example yaml not having the `profile_time_start` and `profile_time_end` keys. New version should have these properly entered in the example
